package mini.os.insta.model;

public enum TipoPeticion {
    LOGIN,
    REGISTRAR,
    PUBLICAR,
    VER_TIMELINE,
    VER_PUBLICACIONES,
    BUSCAR_PERSONAS,
    BUSCAR_HASHTAG,
    INTERACCIONES,
    VER_PERFIL,
    SEGUIR,
    DEJAR_SEGUIR,
    VER_SEGUIDORES,
    VER_SIGUIENDO,
    ACTIVAR_DESACTIVAR,
    CAMBIAR_FOTO,
    ENVIAR_MENSAJE,
    VER_MENSAJES,
    CONVERSACIONES,
    MARCAR_LEIDOS,
    ELIMINAR_CONVERSACION,
    NO_LEIDOS,
    STICKERS_DISPONIBLES,
    IMPORTAR_STICKER
}